"""initial

Revision ID: 947ab1fc1411
Revises: 
Create Date: 2026-04-15 11:26:43.380891

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '947ab1fc1411'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
